### ISSUE TITLE
Asymmetry in wave and readout

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/wave-interference#142]
I've noticed an asymmetry in the wave display and readout. I suspect it could be a consequence of the goal to make the nodes more apparent, but it seems to cause some potential miscommunication about waves too. 

It looks like peak and trough are not symmetric about a "zero" level. There is more black than blue in one period, and on the readout the wave goes lower than it goes high. 

It seems worth noting, and discussing, if this is OK. If possible to make it symmetric that would be better pedagogically. 

![image](https://user-images.githubusercontent.com/5096804/45530644-053c6400-b7a9-11e8-84c1-a5744eb4e338.png)

EDIT by @samreid: notes => nodes

**Comment by arouinfar** [comment]
@kathy-phet I spent some time testing dev.28, and I'm not seeing the same asymmetry in the wave detector.
<img width="787" alt="screen shot 2018-09-17 at 2 31 44 pm" src="https://user-images.githubusercontent.com/8419308/45648656-6e142c80-ba86-11e8-8e5e-2bb3660e7c84.png">
<img width="288" alt="screen shot 2018-09-17 at 2 32 01 pm" src="https://user-images.githubusercontent.com/8419308/45648664-7704fe00-ba86-11e8-9f71-e8de818ba5e3.png">



@samreid can you take a look? The case in @kathy-phet's https://github.com/phetsims/wave-interference/issues/142#issue-360157594 is clearly asymmetric about zero.
<img width="401" alt="screen shot 2018-09-17 at 2 27 28 pm" src="https://user-images.githubusercontent.com/8419308/45648455-d31b5280-ba85-11e8-98aa-9bce4f94bf3c.png">

**Comment by kathy-phet** [comment]
I don’t totally follow. Maybe we table this until Thursday when you can both look at my computer screen with me?

Sent from my iPhone

On Sep 18, 2018, at 6:24 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


I used the spike in #133 (comment)<https://github.com/phetsims/wave-interference/issues/133#issuecomment-422466033> to see if the wave area was matching up with the readout, and it seems closely matched. The probes are at the point at which moving one pixel drops the graph to 0.0.

[image]<https://user-images.githubusercontent.com/679486/45723732-ff130280-bb6f-11e8-9cc2-4c06ab943730.png>

**Comment by samreid** [comment]
I see the asymmetry you are referring to.  My preceding comment was checking for an overall offset in the coordinate mapping.  Here's the function we are using for mapping wave value => color:

![image](https://user-images.githubusercontent.com/679486/45724353-f66ffb80-bb72-11e8-86c6-62e1352eebf6.png)

On April 5, 2018 we decided we wanted to "try out flattening the range for zero amplitude. "  However, in https://github.com/phetsims/wave-interference/issues/89 we discussed the current rendering and decided to go with it, but we did not account for the asymmetry that @kathy-phet pointed out.

We could adjust the graph above, but I'm not sure how it may impact other parts of the sim or prior approved behavior.  I'll schedule this for an upcoming design meeting.

**Comment by arouinfar** [comment]
In yesterday's design meeting, @ariel-phet mentioned that he wasn't particularly worried that the troughs look slightly wider than the peaks.  I can also live with this slight asymmetry (assuming there aren't any issues that arise in the interviews) as it really helps gives the nodes a more defined look.

@kathy-phet suggested that we try linearly scaling the brightness (rather than the current piecewise approach) to see how visible the nodes are. @samreid could you publish a dev version with linear brightness scaling sometime before next Thursday? It'd be nice to compare things side-by-side in design meeting.

I still haven't been able to reproduce the asymmetry in the wave detector readout, which should never occur regardless which brightness mapping we choose.

**Comment by samreid** [comment]
Here's a picture with the original piecewise linear model. Single wave source, no interference, first screen.

```js
          if ( waveValue > 0 ) {
            intensity = Util.linear( 0, 2, CUTOFF, 1, waveValue );
            intensity = Util.clamp( intensity, CUTOFF, 1 );
          }
          else {
            const MIN_SHADE = 0.03; // Stop before 0 because 0 is too jarring
            intensity = Util.linear( -1.5, 0, MIN_SHADE, CUTOFF, waveValue );
            intensity = Util.clamp( intensity, MIN_SHADE, CUTOFF );
          }
```

![image](https://user-images.githubusercontent.com/679486/46023669-564e3100-c0a2-11e8-9cc4-a9b34feca145.png)


Here's a picture of a simple linear model:
```js
          const MIN_SHADE = 0.03; // Stop before 0 because 0 is too jarring

          intensity = Util.linear( -1.5, 2, MIN_SHADE, 1, waveValue );
          intensity = Util.clamp( intensity, MIN_SHADE, 1 );
```

![image](https://user-images.githubusercontent.com/679486/46023690-61a15c80-c0a2-11e8-8374-7de8cad2c581.png)

Just looking at these two data points suggests we may want something in the middle.  But when I look at the Screen 2 interference pattern with the linear scaling, it looks like this:

![image](https://user-images.githubusercontent.com/679486/46023815-b47b1400-c0a2-11e8-8f72-45d643b61c0a.png)

@arouinfar can you please review my notes and advise?

**Comment by arouinfar** [comment]
@samreid can create a dev version with the linear mapping?

**Comment by samreid** [comment]
I committed linear to master and created a dev version: 
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.37/phet/wave-interference_en_phet.html

@arouinfar can you please review and advise?

**Comment by arouinfar** [comment]
Thanks @samreid. I think the linear scaling is a no-go.
I find that the wave is a bit muddier, and the nodes are much harder to spot.

Linear:
![image](https://user-images.githubusercontent.com/8419308/46559508-d26c2400-c8ad-11e8-845e-7003f8e11693.png)

Piecewise:
![image](https://user-images.githubusercontent.com/8419308/46559524-def07c80-c8ad-11e8-952a-49f11aca6f13.png)

> Just looking at these two data points suggests we may want something in the middle.

Agreed @samreid. From the code snippets you posted, I should be able to tweak and test things locally. I'll recommend some values before next week's design meeting.

**Comment by kathy-phet** [comment]
@arouinfar - I wanted to post this Java version shot for comparison.
![image](https://user-images.githubusercontent.com/5096804/46561847-a86b2f80-c8b6-11e8-8b1c-03891c6b15ec.png)

I think the HTML version of the linear model is doing quite well, actually and the nodes are clearer than in the Java version. I worry pretty significantly about the non-physical side effects of rescaling. The correct physics is that the node should not be black or bright blue but should be in mid-blue range with no oscillation. I understand the notion of making it look blacker, but I still struggle with this approach because in fact it shouldn't be blacker.

**Comment by arouinfar** [comment]
I would agree that the linear scaling in HTML5 does look better than Java.  

That said, a motivator for revisiting the linear mapping was the apparent asymmetry between the widths of the maxima and minima. The linear mapping doesn't actually fix the apparent asymmetry, and the maxima now appear quite broad.

Perhaps the solution would be to adjust the piecewise mapping so the y-intercept is somewhere between 0.3 (current) and 0.5 (linear).

| Version | Screenshot | 
|-----|-----|
| Linear |<img src="https://user-images.githubusercontent.com/8419308/46562380-0f89e380-c8b9-11e8-93f0-c7b1ecb0090a.png" width=500>|
| Piecewise |<img src="https://user-images.githubusercontent.com/8419308/46562395-24667700-c8b9-11e8-846b-8b4ed917b017.png" width=500>|
| Linear |<img src="https://user-images.githubusercontent.com/8419308/46562438-47912680-c8b9-11e8-99d9-2b91ade8a006.png" width=500>|
| Piecewise |<img src="https://user-images.githubusercontent.com/8419308/46562419-37794700-c8b9-11e8-95b9-6bdaddbdd654.png" width=500>|

**Comment by arouinfar** [comment]
@samreid can you change the y-intercept of the mapping to 0.4 and publish a dev version?

**Comment by samreid** [comment]
I referred @arouinfar to https://github.com/phetsims/wave-interference/blob/e1c87f1116f995c9cb8f0df25aa0d6fa6462dd02/js/common/view/LatticeCanvasNode.js#L107-L115 and she wants to take a look.  We also noted the asymmetry on the negative side, going from -1.5 instead of 2.  We should check that as well.

**Comment by arouinfar** [comment]
## Current behavior
![image](https://user-images.githubusercontent.com/8419308/47462700-680a1d80-d7a1-11e8-8347-7ce3bb16cf98.png)
![image](https://user-images.githubusercontent.com/8419308/47463150-aa802a00-d7a2-11e8-9476-7ed45c896518.png)

## Experimenting with L113

Changing the negative to -1.5 in [L113](https://github.com/phetsims/wave-interference/blob/e1c87f1116f995c9cb8f0df25aa0d6fa6462dd02/js/common/view/LatticeCanvasNode.js#L113) washes out the minima, which is why I think it was asymmetrically skewed to begin with.
![image](https://user-images.githubusercontent.com/8419308/47462720-72c4b280-d7a1-11e8-98a8-3a144edf2805.png)
![image](https://user-images.githubusercontent.com/8419308/47463168-b23fce80-d7a2-11e8-9be4-5bf438aed122.png)


Increasing the value to -1 really boosts the black, but looks a bit unrealistic.
![image](https://user-images.githubusercontent.com/8419308/47462953-1a41e500-d7a2-11e8-80d5-b9fe7314df60.png)
![image](https://user-images.githubusercontent.com/8419308/47463183-bbc93680-d7a2-11e8-9ad8-cee7502df1e7.png)

## Experimenting with value of CUTOFF

Increasing the CUTOFF defined in [L95](https://github.com/phetsims/wave-interference/blob/e1c87f1116f995c9cb8f0df25aa0d6fa6462dd02/js/common/view/LatticeCanvasNode.js#L95) to 0.4 makes the maxima look a bit too broad.
![image](https://user-images.githubusercontent.com/8419308/47463410-604b7880-d7a3-11e8-942d-dd2f93dce99e.png)
![image](https://user-images.githubusercontent.com/8419308/47463480-9688f800-d7a3-11e8-9874-994f00f560bc.png)

CUTOFF = 0.35 has a better balance between maxima and minima.

<img width="594" alt="screen shot 2018-10-24 at 5 06 02 pm" src="https://user-images.githubusercontent.com/8419308/47466588-1ff1f780-d7af-11e8-803b-4f339130350f.png">
<img width="596" alt="screen shot 2018-10-24 at 5 05 55 pm" src="https://user-images.githubusercontent.com/8419308/47466587-1ff1f780-d7af-11e8-8c31-057a06a07c75.png">


## Final thoughts

Increasing CUTOFF to 0.35 linearizes the color mapping a bit, while maintaining a balance between the widths of the maxima and minima. @samreid can you change `CUTOFF` (see [L95](https://github.com/phetsims/wave-interference/blob/e1c87f1116f995c9cb8f0df25aa0d6fa6462dd02/js/common/view/LatticeCanvasNode.js#L95)) to 0.35 and publish a dev version so the team can take a look?

Here are some side-by-side comparisons.

| CUTOFF=0.3 (Current) | CUTOFF=0.35 | Linear | 
|-----|-----|-----|
|<img src="https://user-images.githubusercontent.com/8419308/47462700-680a1d80-d7a1-11e8-8347-7ce3bb16cf98.png" width=200>|<img width="200" alt="screen shot 2018-10-24 at 5 06 02 pm" src="https://user-images.githubusercontent.com/8419308/47466588-1ff1f780-d7af-11e8-803b-4f339130350f.png">|<img width="200" alt="screen shot 2018-10-24 at 5 37 04 pm" src="https://user-images.githubusercontent.com/8419308/47467401-77926200-d7b3-11e8-934e-4972efa4e388.png">|
|<img width="200" alt="screen shot 2018-10-24 at 5 41 18 pm" src="https://user-images.githubusercontent.com/8419308/47467541-128b3c00-d7b4-11e8-99bc-3dc8eab6114c.png">|<img width="200" alt="screen shot 2018-10-24 at 5 42 58 pm" src="https://user-images.githubusercontent.com/8419308/47467571-49f9e880-d7b4-11e8-9beb-ceaa1ffd632b.png">|<img width="200" alt="screen shot 2018-10-24 at 5 43 49 pm" src="https://user-images.githubusercontent.com/8419308/47467583-66962080-d7b4-11e8-9c7a-697d1c1d0b69.png">|
|<img width="200" alt="screen shot 2018-10-24 at 5 45 18 pm" src="https://user-images.githubusercontent.com/8419308/47467713-f8059280-d7b4-11e8-9e99-be48a00087d2.png">|<img width="200" alt="screen shot 2018-10-24 at 5 45 33 pm" src="https://user-images.githubusercontent.com/8419308/47467742-0fdd1680-d7b5-11e8-9cbd-4028ab752641.png">|<img width="200" alt="screen shot 2018-10-24 at 5 45 55 pm" src="https://user-images.githubusercontent.com/8419308/47467757-1d929c00-d7b5-11e8-92b6-52e119f736dd.png">|
|<img width="200" alt="screen shot 2018-10-24 at 5 47 19 pm" src="https://user-images.githubusercontent.com/8419308/47467765-297e5e00-d7b5-11e8-96c2-6375bdfd76b8.png">|<img width="200" alt="screen shot 2018-10-24 at 5 47 29 pm" src="https://user-images.githubusercontent.com/8419308/47467777-34d18980-d7b5-11e8-9ff6-478e5840fb29.png">|<img width="200" alt="screen shot 2018-10-24 at 5 47 37 pm" src="https://user-images.githubusercontent.com/8419308/47467793-3e5af180-d7b5-11e8-89e9-0487a24d98ff.png">|

**Comment by samreid** [comment]
In the preceding commit, I changed the CUTOFF from 0.3 to 0.35.  I published a dev version with this value here: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.39/phet/wave-interference_en_phet.html.

@arouinfar can you please confirm it has the desired behavior?

**Comment by arouinfar** [comment]
Thanks @samreid. The behavior looks correct to me! I've set up a few scenarios (similar to the table in https://github.com/phetsims/wave-interference/issues/142#issuecomment-432866615) that we can compare in design meeting.

**Comment by arouinfar** [comment]
We reviewed again in design meeting, and @kathy-phet thought `CUTOFF` = 0.4 might be preferable, so @samreid built us a version with that value.

@kathy-phet said she would review, and let us know what she thinks.
* [dev.40](https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.40/phet/wave-interference_en_phet.html): `CUTOFF` = 0.4
* [dev.39](https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.39/phet/wave-interference_en_phet.html): `CUTOFF` = 0.35
* [dev.38](https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.38/phet/wave-interference_en_phet.html): `CUTOFF` = 0.3 (the value we've been using since April)
* [dev.37](https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.37/phet/wave-interference_en_phet.html): Linear mapping

**Comment by arouinfar** [comment]
@kathy-phet we would like to address this issue before this sim goes to dev testing, can you review https://github.com/phetsims/wave-interference/issues/142#issuecomment-433222418?

@ariel-phet can you take a look at the options in https://github.com/phetsims/wave-interference/issues/142#issuecomment-433222418 and let me know what you think? I'm most on board with the color mapping in dev.39 or dev.40, but @kathy-phet had been leaning towards going back to a linear mapping.

The table at the bottom of https://github.com/phetsims/wave-interference/issues/142#issuecomment-432866615 shows some side-by-side comparisons of dev.37, dev.38, and dev.39.

**Comment by ariel-phet** [comment]
@arouinfar @samreid after playing around a bunch and doing side-by-side comparisons, dev.40 and dev.37 are close but with some subtle differences. I think I am pretty sold on dev.40 for a few reasons:

1. There is an ever so slightly gentler feathering of the peak of the wave when looking at water waves from a single source. To me this makes the waves look a bit more natural. This effect is pretty subtle however. (I did step by step comparisons)

2. For the defaults on interference dev.37 is more washed out in terms of clarity of the nodes than dev.40

3. For the range of colors dev.40 seems to have better clarity of nodes/sharper contrast for the interference screen

4. On the slits screen for equal conditions, dev.37 and dev.40 look nearly identical (perhaps with a plane wave not much difference).

**Comment by arouinfar** [comment]
Thanks @ariel-phet. During design meeting, dev.40 seemed acceptable to @kathy-phet, so let's go with that @samreid.
