### ISSUE TITLE
Improve interference from "reflection" in single wave light screen for v2

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/wave-interference#349]
When we just have one source in the first or second screens, the "reflection" or lack of complete absorption that is happening on the far right of the lattice is causing interference to be visible on the light screen. I would like to spend some time investigating options for reducing this for this v2 work (see oscillatory behavior here). Can the model be tweaked so that after the wave has propogated out of the window and to the edge it can no longer propogate backwards? Perhaps consulting with Mike D for additional options on suppressing that backward reflection? (Note - I am connecting this to a reflection of the back of the lattice because it takes a while for the oscillations to appear and at first they are not there). 
![image](https://user-images.githubusercontent.com/5096804/54144487-7162f200-43f1-11e9-81da-78121d5bdde5.png)

**Comment by arouinfar** [comment]
@samreid is it possible that increasing the lattice size in https://github.com/phetsims/wave-interference/issues/315 could be the culprit here? 

The apparent interference pattern in screen on Waves was previously discussed/addressed in https://github.com/phetsims/wave-interference/issues/171 and https://github.com/phetsims/wave-interference/issues/197. The brightness of the screen has also been extensively discussed in https://github.com/phetsims/wave-interference/issues/161. Would we need to revisit/recalibrate the work done in these issues?

**Comment by arouinfar** [comment]
Sorry for the potato quality, but here's a comparison of dev.61 (top) and rc.2 (bottom). 

![dev 61-screen](https://user-images.githubusercontent.com/8419308/54159246-2d341980-4412-11e9-9526-91d0c45ce749.gif)
![rc 2-screen](https://user-images.githubusercontent.com/8419308/54159247-2dccb000-4412-11e9-9410-955d93f84521.gif)

**Comment by samreid** [comment]
On Thursday, March 21, @kathy-phet reiterated that it would be good to eliminate this interior reflection that is leading to a pattern in the signal.  I previously experimented with several approaches to eliminate or reduce reflections at the edge of the barriers, and the best approach we have implemented so far is described in this comment: https://github.com/phetsims/wave-interference/issues/197#issuecomment-442598255

This approach has better behavior than any of the exponential decay function envelopes we tried, but it does not eliminate reflections 100%.

I mentioned to @kathy-phet that as a last resort, we could superimpose the desired result on the screen and graph.

It would be good to touch base on this issue before I spend more time on it.

**Comment by samreid** [comment]
> The brightness of the screen has also been extensively discussed in #161. Would we need to revisit/recalibrate the work done in these issues?

Note we expect to perform some recalibration in https://github.com/phetsims/wave-interference/issues/323#issuecomment-457005586

**Comment by samreid** [comment]
In discussion, @arouinfar and I decided to try a hollywood or larger averaging window, only for the waves screen.  You would still see this problem on the interference screen if one source is on, but that is a rarer case.

**Comment by samreid** [comment]
For the screens with a single source, I increased the averaging window for the screen.  This smooths out the noise. @arouinfar can you please review?

**Comment by arouinfar** [comment]
@samreid this looks great! Since the Waves screen has its own averaging window, I think it would be good to also change the brightness calibration for Waves too. With the amplitude at 50%, the brightness is quite low, and would seem closer to the brightness I would expect at 10%.

| Amplitude | Screen Brightness |
| --- | --- |
| 100% | <img src="https://user-images.githubusercontent.com/8419308/55645848-e6c6a600-5796-11e9-8ce5-594370b184d7.png" width=50> |
| 50% | <img src="https://user-images.githubusercontent.com/8419308/55645721-83d50f00-5796-11e9-958d-f253a6f73aad.png" width=50> |
| 10% | <img src="https://user-images.githubusercontent.com/8419308/55645939-1d9cbc00-5797-11e9-8f7a-102c15755db2.png" width=50> |

**Comment by samreid** [comment]
If I multiply the overall brightness scaling by a factor of 3, the 50% value seems better:

![image](https://user-images.githubusercontent.com/679486/55650827-031d0f80-57a4-11e9-9049-b106e54c8b81.png)

but even 25% seems very dark:

![image](https://user-images.githubusercontent.com/679486/55650851-19c36680-57a4-11e9-8f15-1af025816fd1.png)

Do you think we will need to introduce a nonlinearity for this display?

**Comment by samreid** [comment]
@arouinfar and I reviewed this and decided we would like to try a piecewise linear function to get better behavior across the range of intensities.

**Comment by samreid** [comment]
I committed an initial version for this, @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
@samreid the updated brightness on Waves looks great!

However, the screen is broken elsewhere in the sim. The intensity graph appears undisturbed, though.
![image](https://user-images.githubusercontent.com/8419308/55748066-f21a0b80-59fa-11e9-9ff0-a6171a2f7766.png)
![image](https://user-images.githubusercontent.com/8419308/55748103-09f18f80-59fb-11e9-95bd-02845270bcb8.png)
![image](https://user-images.githubusercontent.com/8419308/55748171-31485c80-59fb-11e9-851b-d1dbcb089b2a.png)
![image](https://user-images.githubusercontent.com/8419308/55748145-2261aa00-59fb-11e9-80e3-c5916eabe4c7.png)

**Comment by samreid** [comment]
Good catch, thanks!  I'll take a look.

**Comment by samreid** [comment]
I committed a proposed fix, can you please take a look on phettest?

**Comment by arouinfar** [comment]
Looks great @samreid! I'll tag for design meeting review.

**Comment by samreid** [comment]
Raw notes for archival purposes, in case we come back to this.

80% (default) 0.13
100% 0.21 (oversaturated)
50% => 0.05 (looks good)
40% => 0.036 (this is what 25% should look like)
30% => 0.019 (this is what 10% should look like)

Maybe take sqrt for the display?  This idea did not pan out quickly, we investigated linear piecewise instead.
```
amplitude intensity brightess                            desired brightness
100% 0.2096934692889395 0.9063853228610702 fully bright  0.9
80% 0.13422634397144692 0.5801839634279833 good          0.5
50% 0.05372277438413573 0.23221292666039975 too dim      0.4
20% 0.008937089269640335 0.03862994193652949             0.3
0% 0.000000000000000000 0.00000000000000000 off          0.0

new piecewiselinearfunction([0,0,  0.008, 0.3,  0.05,0.4,  0.134,0.5, 0.2,0.9]  )
```

**Comment by samreid** [comment]
In the design meeting, we agreed this is looking much better.  @kathy-phet said she will take a closer look later on.

**Comment by samreid** [comment]
@ariel-phet can you help move this issue forward?

**Comment by ariel-phet** [comment]
@samreid said proposed version is in Master. Will take a look.

**Comment by ariel-phet** [comment]
@samreid @arouinfar I am tempted to go ahead and close this issue. The fix appears to address the areas of concern. I will note that even with the fix the interference can still be seen with a single source that is slightly off center. But really on the interference screen both sources being "on" is the pedagogically useful case.

![interference](https://user-images.githubusercontent.com/4051174/59813668-96f47700-92cf-11e9-9b4a-300e8ece7936.PNG)

**Comment by arouinfar** [comment]
Discussed in 6/20/19 design meeting, and decided that we can defer this issue.

The current behavior is an improvement over 1.0, but we would like to leave this open for the possibility of future investigation/improvements.

**Comment by samreid** [comment]
Based on the above 2 comments I will remove this issue from the 2.1 publication project board, adding that in the future we could eventually rewrite the entire model to use the analytical model developed for quantum wave interference, which is noiseless and reflectionless but would be a massive undertaking/overhaul of the entire model.
